/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'TanelEST' at '2/18/17 3:54 PM' with Gradle 2.13
 *
 * @author TanelEST, @date 2/18/17 3:54 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
